export const CLIENTE_LIST_REQUEST = "CLIENTE_LIST_REQUEST";
export const CLIENTE_LIST_SUCCESS = "CLIENTE_LIST_SUCCESS";
export const CLIENTE_LIST_FAIL = "CLIENTE_LIST_FAIL";

export const CLIENTE_DETAILS_REQUEST = "CLIENTE_DETAILS_REQUEST";
export const CLIENTE_DETAILS_SUCCESS = "CLIENTE_DETAILS_SUCCESS";
export const CLIENTE_DETAILS_FAIL = "CLIENTE_DETAILS_FAIL";
