export const PEDIDO_LIST_REQUEST = "PEDIDO_LIST_REQUEST";
export const PEDIDO_LIST_SUCCESS = "PEDIDO_LIST_SUCCESS";
export const PEDIDO_LIST_FAIL = "PEDIDO_LIST_FAIL";

export const PEDIDO_DETAILS_REQUEST = "PEDIDO_DETAILS_REQUEST";
export const PEDIDO_DETAILS_SUCCESS = "PEDIDO_DETAILS_SUCCESS";
export const PEDIDO_DETAILS_FAIL = "PEDIDO_DETAILS_FAIL";
