export const VENDEDOR_LIST_REQUEST = "VENDEDOR_LIST_REQUEST";
export const VENDEDOR_LIST_SUCCESS = "VENDEDOR_LIST_SUCCESS";
export const VENDEDOR_LIST_FAIL = "VENDEDOR_LIST_FAIL";

export const VENDEDOR_DETAILS_REQUEST = "VENDEDOR_DETAILS_REQUEST";
export const VENDEDOR_DETAILS_SUCCESS = "VENDEDOR_DETAILS_SUCCESS";
export const VENDEDOR_DETAILS_FAIL = "VENDEDOR_DETAILS_FAIL";
